### ISSUE TITLE
3-5 of your favorite books

### ISSUE THREAD

**Issue by loraxgirl** [QuarantineNightOwls/Project2#6]
please let me know 3 to 5 of your favorite books that you would like on our coffee shop bookshelf (title and author please)

**Comment by skang91** [comment]
1. What I Know For Sure - by Oprah Winfrey
2. Outliers-  by Malcolm Gladwell
3. Sherlock Holmes - by Conan Doyle

**Comment by benbaba2525** [comment]
1. The Falling in Love Montage
 Ciara Smyth

2. Late to the Party
by Kelly Quindlen

3. The Night Circus
by Erin Morgenstern


4. A Game of Thrones
by George R.R. Martin

**Comment by GitJoeCode** [comment]
https://www.goodreads.com/book/show/9361589-the-night-circus?from_search=true&from_srp=true&qid=XYuwqNDqVZ&rank=1

https://www.goodreads.com/book/show/33600.Shantaram?from_search=true&from_srp=true&qid=wyATiR84Tq&rank=1

https://www.goodreads.com/book/show/14995.Odd_Thomas?from_search=true&from_srp=true&qid=6JPdMtBURu&rank=1

https://www.goodreads.com/book/show/10357575-1q84?from_search=true&from_srp=true&qid=2cpOK3XRgQ&rank=1

https://www.goodreads.com/book/show/18144590-the-alchemist?from_search=true&from_srp=true&qid=zemfIdA4gi&rank=1

will include some others and can recommend plenty more as well

https://www.goodreads.com/book/show/42744560-cormoran-strike-series-robert-galbraith-4-books-collection-set?from_search=true&from_srp=true&qid=PBPQoXCze5&rank=1

https://www.goodreads.com/book/show/997600.The_Wump_World?from_search=true&from_srp=true&qid=wZi7VC4R6d&rank=1
